export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SET_TODO = 'SET_TODO'

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL'

export const FETCH_TODO_INIT = 'FETCH_TODO_INIT'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const FETCH_TODO_FAIL = 'FETCH_TODO_FAIL'

export const REMOVE_TODO_INIT = 'REMOVE_TODO_INIT'
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS'
export const REMOVE_TODO_FAIL = 'REMOVE_TODO_FAIL'

export const FILTER_TODO_INIT = 'FILTER_TODO_INIT'
